name: Master Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: master-workflow
  cancel-in-progress: true

jobs:
  build-dep:
    name: Build installable deb package
    uses: './.github/workflows/wf-build-dep.yaml'
    secrets: inherit
