name: Update Connector Orchestrator code

on:
  workflow_call:
    inputs:
      run_id:
        description: 'The run ID to download artifacts from.'
        required: true
        type: string
      repository_owner:
        description: 'The source repository to download artifacts from.'
        required: true
        type: string
        default: 'xip-online-applications'
      repository:
        description: 'The source repository to download artifacts from.'
        required: true
        type: string
        default: 'xod-core'
      artifact_name:
        description: 'The name of the artifact to download.'
        required: true
        type: string
        default: transai-connector-orchestrator

jobs:
  update-code:
    name: Update Connector Orchestrator code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cleanup current code
        run: make cleanup

      - name: Generate download artifact token
        id: token-download-artifact
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.XOD_CORE_APP_ID }}
          private-key: ${{ secrets.XOD_CORE_APP_PRIVATE_KEY }}
          permission-actions: read
          repositories: ${{ inputs.repository }}

      - name: Download code artifact
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ steps.token-download-artifact.outputs.token }}
          name: ${{ inputs.artifact_name }}
          repository: ${{ inputs.repository_owner }}/${{ inputs.repository }}
          run-id: ${{ inputs.run_id }}

      - name: Generate command and push token
        id: token-commit-push
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.XOD_CORE_APP_ID }}
          private-key: ${{ secrets.XOD_CORE_APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Git commit and push updated code
        env:
          GITHUB_TOKEN: ${{ steps.token-commit-push.outputs.token }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git status
          git commit -m "chore: update connector orchestrator code to latest version from ${{ inputs.repository_owner }}/${{ inputs.repository }} run ID ${{ inputs.run_id }}" || echo "No changes to commit"
          git push
